version: "3.9"
services:
  backend:
    build:
      context: ./bookLibrary-api/bookLibraryApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./booklibrary-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "test$%¨&*()123"
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"
